# Sniperkit-Bot
# - Status: analyzed

---
version: '3'

services:

  redis:
    name: dtk-redis
    image: redis:4-alpine
    restart: always
    ports:
    - 6379:6379

  mcc-cli:
    name: snk-mcc-cli
    image: sniperkit/snk-mcc-cli:3.7-alpine
    environment:
    - DISKV_BASE_DIR=./diskv
    volumes:
    - "diskv:/diskv"
    ports:
    - 8000:8000
    depends_on:
    - splash
    restart: always

  mcc-api:
    name: mcc-api
    image: sniperkit/snk-mcc-api:3.7-alpine
    environment:
    - DISKV_BASE_DIR=./diskv
    volumes:
    - "diskv:/diskv"
    ports:
    - 8000:8000
    restart: always

volumes:
  diskv: 
  - "./shared/data/cache/diskv:/diskv"