version: '3'

services:

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    
  testserver:
    image: sniperkit/mcc-testserver
    environment:
      - MCC_TEST=testserver:12345
    ports:
      - "12345:12345"
    depends_on:
      - splash
    restart: always
  